GET http://localhost:3000/include-list

POST http://localhost:3000/include-list
Content-Type: application/json

{
"task": "annotate",
"active": true
} 

PATCH http://localhost:3000/include-list/61ba8653871e0da1e99d7ba8
Content-Type: application/json

{
  "task": "annotate",
  "active": false
}

