GET http://localhost:3000/guides

GET http://localhost:3000/guides?namesOnly=true

GET http://localhost:3000/guides/61b411bd6bda96f16e5d1b6a

GET http://localhost:3000/guides/needed/annotate-and-categorize-objects-in-an-image-using-a-bounding-box

POST http://localhost:3000/guides
Content-Type: application/json

{
  "name": "Hola, soy una guia",
  "keywords": ["hola", "soy", "una", "guia"],
  "collections": ["entrada1", "entrada2"]
}

PATCH http://localhost:3000/guides/Youtube
Content-Type: application/json

{
  "name": "Youtube",
  "keywords": []
}

DELETE http://localhost:3000/guides/61ba8653871e0da1e99d7ba8
