GET http://localhost:3001/guides

GET http://localhost:3001/guides?namesOnly=true

GET http://localhost:3001/guides/61bcd6c37143bfe3b669f818

GET http://localhost:3001/guides/needed/rate-content-of-animated-gifs-adult-content

POST http://localhost:3001/guides
Content-Type: application/json

{
  "name": "Hola, soy una guia",
  "keywords": ["hola", "soy", "una", "guia"],
  "collections": ["entrada1", "entrada2"]
}

POST http://localhost:3001/guides/61bcd6c37143bfe3b669f818
Content-Type: application/json

{
  "task": {
    "identifier": "imageUrl",
    "response": "this is a response"
  }
}

PATCH http://localhost:3001/guides/Youtube
Content-Type: application/json

{
  "name": "Youtube",
  "keywords": []
}

DELETE http://localhost:3001/guides/61ba8653871e0da1e99d7ba8
