GET http://localhost:3000/task-guide-info/annotate-and-categorize-objects-in-an-image-using-a-bounding-box

PATCH http://localhost:3000/task-guide-info/annotate-and-categorize-objects-in-an-image-using-a-bounding-box
Content-Type: application/json

{
  "script_id": "none"
}

